# Creating the final dataset

### ESPN

In [1]:
import pandas as pd

In [7]:
ESPN_data = '1-ESPN-health-data/ESPN_stadium_violations.CSV'

In [8]:
ESPN = pd.read_csv(ESPN_data)

In [9]:
ESPN

,MLB Team,Stadium Name,Seating Capacity,"City, State",State Abbreviation,Venue Score,Area Score,Total Inspections,Critical Inspections Found,Critical Score in percentage,Violations
0,Diamondbacks,Chase Field,48519,"Phoenix, Arizona",AZ,0.20,0.25,96,33,34.38,"[{'image': 'condition', 'date': 'Outdated food..."
1,Padres,Petco Park,40162,"San Diego, California",CA,0.09,0.09,168,28,16.67,"[{'image': 'temperature', 'date': 'Food too wa..."
2,Angels,Angel Stadium,45050,"Anaheim, California",CA,0.17,0.46,134,26,19.40,"[{'image': 'pests', 'date': 'Live roaches', 'c..."
3,Athletics,Oakland-Alameda County Coliseum,63024,"Oakland, California",CA,0.18,1.32,119,27,22.69,"[{'image': 'employee', 'date': 'Handwashing is..."
4,Giants,AT&T Park,41915,"San Francisco, California",CA,0.10,0.25,162,40,24.69,"[{'image': 'equipment', 'date': 'No running wa..."
5,Dodgers,Dodger Stadium,56000,"Los Angeles, California",CA,0.29,0.96,191,61,31.94,"[{'image': 'pests', 'date': 'Multiple problems..."
6,Rockies,Coors Field,50144,"Denver, Colorado",CO,1.14,1.50,107,77,71.96,"[{'image': 'pests', 'date': 'Mouse feces', 'co..."
7,Nationals,Nationals Park,41546,"Washington, District of Columbia",DC,0.28,0.00,27,14,51.85,"[{'image': 'condition', 'date': 'Chip containe..."
8,Marlins,Marlins Park,37442,"Miami, Florida",FL,0.13,1.07,21,3,14.29,"[{'image': 'temperature', 'date': 'Incorrect t..."
9,Rays,Tropicana Field,31042,"St. Petersburg, Florida",FL,0.40,1.07,79,25,31.65,"[{'image': 'employee', 'date': 'Various food p..."
10,Braves,SunTrust Park,41149,"Atlanta, Georgia",GA,0.34,0.78,83,28,33.73,"[{'image': 'temperature', 'date': 'Food too wa..."
11,Cubs,Wrigley Field,42495,"Chicago, Illinois",IL,0.31,0.20,26,8,30.77,"[{'image': 'condition', 'date': 'Issue with to..."
12,White Sox,Guaranteed Rate Field,40615,"Chicago, Illinois",IL,0.57,0.20,68,38,55.88,"[{'image': 'temperature', 'date': 'Hot and bra..."
13,Red Sox,Fenway Park,37755,"Boston, Massachusetts",MA,0.09,0.62,58,10,17.24,"[{'image': 'pests', 'date': 'Fruit flies', 'co..."
14,Orioles,Oriole Park at Camden Yards,45971,"Baltimore, Maryland",MD,0.10,0.55,96,15,15.63,"[{'image': 'pests', 'date': 'Rodent activities..."
15,Tigers,Comerica Park,41083,"Detroit, Michigan",MI,0.53,0.70,52,21,40.38,"[{'image': 'temperature', 'date': 'Food too wa..."
16,Twins,Target Field,39504,"Minneapolis, Minnesota",MN,0.61,0.00,113,57,50.44,"[{'image': 'pests', 'date': 'Rodents and insec..."
17,Cardinals,Busch Stadium,43975,"St. Louis, Missouri",MO,0.17,0.39,62,14,22.58,"[{'image': 'temperature', 'date': 'Improper fo..."
18,Royals,Kauffman Stadium,37903,"Kansas City, Missouri",MO,0.56,1.36,106,44,41.51,"[{'image': 'condition', 'date': 'Improper rehe..."
19,Mets,Citi Field,41922,"Queens, New York",NY,0.35,1.47,58,32,55.17,"[{'image': 'temperature', 'date': 'Food too co..."
20,Yankees,Yankee Stadium,56886,"Bronx, New York",NY,0.67,1.47,43,34,79.07,"[{'image': 'condition', 'date': 'Food handling..."
21,Indians,Progressive Field,35041,"Cleveland, Ohio",OH,0.04,0.00,133,12,9.02,"[{'image': 'temperature', 'date': 'Food too co..."
22,Reds,Great American Ball Park,42036,"Cincinnati, Ohio",OH,0.20,0.00,52,26,50.00,"[{'image': 'condition', 'date': 'Old food', 'c..."
23,Blue Jays,Rogers Centre,49282,"Toronto, Ontario",ON,0.21,0.44,63,31,49.21,"[{'image': 'equipment', 'date': 'Unclean surfa..."
24,Pirates,PNC Park,38496,"Pittsburgh, Pennsylvania",PA,0.20,0.98,65,18,27.69,"[{'image': 'temperature', 'date': 'Food too co..."
25,Phillies,Citizens Bank Park,43651,"Philadelphia, Pennsylvania",PA,0.35,0.00,101,43,42.57,"[{'image': 'condition', 'date': 'Food prep on ..."
26,Astros,Minute Maid Park,40963,"Houston, Texas",TX,0.19,1.28,70,20,28.57,"[{'image': 'equipment', 'date': 'Slime in ice ..."
27,Rangers,Globe Life Park in Arlington,48114,"Arlington, Texas",TX,1.22,0.00,156,111,71.15,"[{'image': 'pests', 'date': 'Live roach', 'cop..."
28,Mariners,Safeco Field,47943,"Seattle, Washington",WA,0.10,0.66,92,20,21.74,"[{'image': 'equipment', 'date': 'Handwashing i..."
29,Brewers,Miller Park,41900,"Milwaukee, Wisconsin",WI,0.10,0.42,115,10,8.70,"[{'image': 'condition', 'date': 'Out-of-date f..."

In [10]:
ESPN.columns

Index(['MLB Team', 'Stadium Name', 'Seating Capacity', 'City, State',
       'State Abbreviation', 'Venue Score', 'Area Score', 'Total Inspections',
       'Critical Inspections Found', 'Critical Score in percentage',
       'Violations'],
      dtype='object')

In [11]:
ESPN.shape

(30, 11)

### Stadium Stats from Baseball-reference.com

In [12]:
team_stats = '3-Baseball-reference-team-data/Team_stats_2017.CSV'

In [13]:
stats = pd.read_csv(team_stats)

In [14]:
stats

,Rk,Tm,Lg,G,W,L,W-L%,R,RA,Rdiff,Home,Road
0,1.0,Dodgers,NL,162.0,104,58,0.642,4.8,3.6,1.2,57-24,47-34
1,2.0,Indians,AL,162.0,102,60,0.630,5.0,3.5,1.6,49-32,53-28
2,3.0,Astros,AL,162.0,101,61,0.624,5.5,4.3,1.2,48-33,53-28
3,4.0,Nationals,NL,162.0,97,65,0.599,5.1,4.1,0.9,47-34,50-31
4,5.0,Red Sox,AL,162.0,93,69,0.574,4.8,4.1,0.7,48-33,45-36
5,6.0,Diamondbacks,NL,162.0,93,69,0.574,5.0,4.1,0.9,52-29,41-40
6,7.0,Cubs,NL,162.0,92,70,0.568,5.1,4.3,0.8,48-33,44-37
7,8.0,Yankees,AL,162.0,91,71,0.562,5.3,4.1,1.2,51-30,40-41
8,9.0,Rockies,NL,162.0,87,75,0.537,5.1,4.7,0.4,46-35,41-40
9,10.0,Brewers,NL,162.0,86,76,0.531,4.5,4.3,0.2,46-38,40-38
10,11.0,Twins,AL,162.0,85,77,0.525,5.0,4.9,0.2,41-40,44-37
11,12.0,Cardinals,NL,162.0,83,79,0.512,4.7,4.4,0.3,44-37,39-42
12,13.0,Angels,AL,162.0,80,82,0.494,4.4,4.4,0.0,43-38,37-44
13,14.0,Royals,AL,162.0,80,82,0.494,4.3,4.9,-0.5,43-38,37-44
14,15.0,Rays,AL,162.0,80,82,0.494,4.3,4.3,-0.1,42-39,38-43
15,16.0,Mariners,AL,162.0,78,84,0.481,4.6,4.8,-0.1,40-41,38-43
16,17.0,Rangers,AL,162.0,78,84,0.481,4.9,5.0,-0.1,41-40,37-44
17,18.0,Marlins,NL,162.0,77,85,0.475,4.8,5.1,-0.3,42-36,35-49
18,19.0,Blue Jays,AL,162.0,76,86,0.469,4.3,4.8,-0.6,42-39,34-47
19,20.0,Pirates,NL,162.0,75,87,0.463,4.1,4.5,-0.4,44-37,31-50
20,21.0,Athletics,AL,162.0,75,87,0.463,4.6,5.1,-0.5,46-35,29-52
21,22.0,Orioles,AL,162.0,75,87,0.463,4.6,5.2,-0.6,46-35,29-52
22,23.0,Braves,NL,162.0,72,90,0.444,4.5,5.1,-0.5,37-44,35-46
23,24.0,Padres,NL,162.0,71,91,0.438,3.7,5.0,-1.3,43-38,28-53
24,25.0,Mets,NL,162.0,70,92,0.432,4.5,5.3,-0.8,37-44,33-48
25,26.0,Reds,NL,162.0,68,94,0.420,4.6,5.4,-0.7,39-42,29-52
26,27.0,White Sox,AL,162.0,67,95,0.414,4.4,5.1,-0.7,39-42,28-53
27,28.0,Phillies,NL,162.0,66,96,0.407,4.3,4.8,-0.6,39-42,27-54
28,29.0,Tigers,AL,162.0,64,98,0.395,4.5,5.5,-1.0,34-47,30-51
29,30.0,Giants,NL,162.0,64,98,0.395,3.9,4.8,-0.8,38-43,26-55
30,NaN,Avg,NaN,NaN,81,81,0.500,4.6,4.6,NaN,43-37,37-43

In [18]:
team_attendance = '3-Baseball-reference-team-data/Team_attendance_2017.CSV'

In [19]:
attendance = pd.read_csv(team_attendance)

In [20]:
attendance

,Tm,Attendance,Attend/G,BPF (Batting Park Factor - > 100 favors batters),PPF (Pitching Park Factor - > 100 favors batters),Est. Payroll,Time
0,Diamondbacks,2134375,26350,108,108,"$106,580,200",3:09
1,Braves,2505252,30929,100,100,"$119,705,250",3:04
2,Orioles,2028424,25042,97,99,"$161,621,633",3:09
3,Red Sox,2917678,36021,105,104,"$200,550,750",3:20
4,Cubs,3199562,39501,103,101,"$177,210,667",3:09
5,White Sox,1629470,20117,97,98,"$97,842,000",3:10
6,Reds,1836917,22678,101,103,"$79,315,786",3:03
7,Indians,2048138,25286,106,104,"$114,427,167",3:06
8,Rockies,2953650,36465,117,116,"$106,650,000",3:11
9,Tigers,2321599,28662,101,102,"$118,375,600",3:14
10,Astros,2403671,29675,94,93,"$157,656,400",3:10
11,Royals,2220370,27412,101,102,"$127,555,817",3:02
12,Angels,3019585,37279,97,97,"$181,125,500",3:11
13,Dodgers,3765856,46492,96,95,"$201,466,263",3:11
14,Marlins,1583014,20295,90,91,"$111,591,100",3:06
15,Brewers,2627705,31282,101,101,"$68,439,300",3:10
16,Twins,2051279,25324,100,101,"$103,932,500",3:11
17,Mets,2460622,30378,94,95,"$176,615,252",3:09
18,Yankees,3154938,38950,104,103,"$182,424,700",3:16
19,Athletics,1475721,18219,95,95,"$51,560,000",3:09
20,Phillies,1905354,23523,98,99,"$86,276,000",3:08
21,Pirates,1919447,23697,97,98,"$102,953,333",3:07
22,Padres,2138491,26401,95,97,"$49,248,767",3:00
23,Mariners,2135445,26364,95,95,"$172,438,700",3:06
24,Giants,3303652,40786,98,98,"$177,399,833",3:04
25,Cardinals,3448337,42572,98,97,"$129,652,933",3:04
26,Rays,1253619,15477,96,96,"$79,473,033",3:13
27,Rangers,2507760,30960,110,110,"$207,326,274",3:13
28,Blue Jays,3203886,39554,101,102,"$158,890,575",3:09
29,Nationals,2524980,31173,104,103,"$175,587,301",3:09

### Fan Review Scores

In [18]:
review_scores = '4-Voice-of-Fan-Report-2017/Voice-of-fan-report-2017-averages.CSV'

In [19]:
scores = pd.read_csv(review_scores)

In [20]:
scores

,Stadium,Facility,Family,Fan Experience,Food and Drink,Average Score
0,Oriole Park at Camden Yards,0.757803,0.752108,0.873283,0.687303,0.767624
1,PNC Park,0.743191,0.786538,0.926634,0.607895,0.766065
2,AT&T Park,0.693962,0.742471,0.918825,0.696970,0.763057
3,Safeco Field,0.702100,0.736655,0.853112,0.694370,0.746559
4,Kauffman Stadium,0.730978,0.771020,0.873270,0.549474,0.731185
5,Great American Ball Park,0.717445,0.730711,0.887528,0.588235,0.730980
6,Progressive Field,0.713092,0.699588,0.842742,0.666667,0.730522
7,Coors Field,0.636495,0.766744,0.880915,0.626043,0.727549
8,Petco Park,0.630174,0.720792,0.819393,0.678632,0.712248
9,Citizens Bank Park,0.674731,0.609562,0.854957,0.699583,0.709708
10,Busch Stadium,0.744059,0.720755,0.893911,0.471616,0.707585
11,Comerica Park,0.653085,0.751278,0.820211,0.604790,0.707341
12,Miller Park,0.559290,0.750820,0.814588,0.698026,0.705681
13,Globe Life Park,0.710027,0.767773,0.816216,0.527187,0.705301
14,Chase Field,0.691044,0.705714,0.778833,0.538860,0.678613
15,Target Field,0.728507,0.388889,0.812865,0.728223,0.664621
16,Citi Field,0.569429,0.624021,0.795670,0.618954,0.652018
17,Angel Stadium of Anaheim,0.582222,0.761290,0.753766,0.448095,0.636343
18,Minute Maid Park,0.599702,0.626374,0.810563,0.443742,0.620095
19,Guaranteed Rate Field,0.413428,0.549020,0.719064,0.749623,0.607783
20,Fenway Park,0.507911,0.699333,0.805107,0.396061,0.602103
21,Tropicana Field,0.570652,0.692615,0.659910,0.411371,0.583637
22,Nationals Park,0.469043,0.556522,0.746806,0.457818,0.557547
23,Marlins Park,0.470109,0.479224,0.727835,0.474614,0.537945
24,Wrigley Field,0.367684,0.597533,0.781117,0.370629,0.529241
25,Yankee Stadium,0.505774,0.442308,0.681514,0.337500,0.491774
26,Dodger Stadium,0.072146,0.603896,0.690888,0.323890,0.422705
27,Rogers Centre,0.568042,0.426791,0.706195,-0.080000,0.405257
28,SunTrust Park,0.116279,0.515571,0.612903,0.290780,0.383883
29,Oakland-Alameda County Coliseum,-0.031818,0.507937,0.434921,-0.051136,0.214976

### Weather Data

In [29]:
weather_temp = 'stadium_temp_list.csv'

In [30]:
temp = pd.read_csv(weather_temp)

In [31]:
temp

,Location,Average Temperature May-Oct 2017,1981-2010 Average,Anomaly
0,"Phoenix, Arizona",89.0,87.5,1.5
1,"Anaheim, California",71.7,69.6,2.1
2,"Los Angeles, California",69.4,66.7,2.7
3,"Oakland, California",68.5,66.5,2.0
4,"San Diego, California",70.4,68.3,2.1
5,"San Francisco, California",64.7,62.4,2.3
6,"Denver, Colorado",64.3,63.8,0.5
7,"Miami, Florida",82.7,81.8,0.9
8,"Tampa, Florida",82.4,81.0,1.4
9,"Atlanta, Georgia",74.6,74.5,0.1
10,"Chicago, Illinois",67.2,65.9,1.3
11,"Baltimore, Maryland",69.8,68.8,1.0
12,"Boston, Massachusetts",66.5,64.8,1.7
13,"Detroit, Michigan",66.6,65.3,1.3
14,"Minneapolis, Minnesota",65.4,64.3,1.1
15,"Kansas City, Missouri",69.7,69.8,-0.1
16,"St. Louis, Missouri",73.2,71.7,1.5
17,"Bronx, New York",69.8,68.8,1.0
18,"Queens, New York",71.2,69.8,1.4
19,"Cincinnati, Ohio",68.1,67.8,0.3
20,"Cleveland, Ohio",67.0,65.9,1.1
21,"Toronto, Ontario (Canada)",NaN,NaN,NaN
22,"Philadelphia, Pennsylvania",71.3,69.8,1.5
23,"Pittsburgh, Pennsylvania",66.5,64.7,1.8
24,"Arlington, Texas",77.8,77.7,0.1
25,"Houston, Texas",81.4,80.2,1.2
26,"Seattle, Washington",62.7,61.2,1.5
27,"Milwaukee, Wisconsin",65.3,64.0,1.3
28,"Washington, District of Columbia",73.2,71.9,1.3

In [32]:
weather_precip = 'stadium_precip_list.CSV'

In [33]:
precip = pd.read_csv(weather_precip)

In [34]:
precip

,Location,Total Precipitation May-Oct 2017,1981-2010 Average,Anomaly
0,"Phoenix, Arizona",2.34,3.40,-1.06
1,"Anaheim, California",0.68,1.09,-0.41
2,"Los Angeles, California",0.20,1.15,-0.95
3,"Oakland, California",0.35,2.14,-1.79
4,"San Diego, California",1.01,0.96,0.05
5,"San Francisco, California",0.47,1.74,-1.27
6,"Denver, Colorado",10.38,10.29,0.09
7,"Miami, Florida",67.28,46.64,20.64
8,"Tampa, Florida",38.83,32.16,6.67
9,"Atlanta, Georgia",28.59,24.67,3.92
10,"Chicago, Illinois",25.94,22.11,3.83
11,"Baltimore, Maryland",23.69,22.17,1.52
12,"Boston, Massachusetts",21.80,21.26,0.54
13,"Detroit, Michigan",16.52,19.06,-2.54
14,"Minneapolis, Minnesota",24.46,21.46,3.00
15,"Kansas City, Missouri",34.67,26.58,8.09
16,"St. Louis, Missouri",17.40,22.54,-5.14
17,"Bronx, New York",24.87,26.33,-1.46
18,"Queens, New York",23.85,23.86,-0.01
19,"Cincinnati, Ohio",26.81,22.06,4.75
20,"Cleveland, Ohio",20.17,20.95,-0.78
21,"Toronto, Ontario (Canada)",NaN,NaN,NaN
22,"Philadelphia, Pennsylvania",27.13,21.94,5.19
23,"Pittsburgh, Pennsylvania",22.68,20.97,1.71
24,"Arlington, Texas",20.58,20.40,0.18
25,"Houston, Texas",56.15,32.31,23.84
26,"Seattle, Washington",9.23,10.02,-0.79
27,"Milwaukee, Wisconsin",18.31,20.78,-2.47
28,"Washington, District of Columbia",23.87,21.55,2.32